name: Project Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download project from git
        uses: actions/checkout@v3

      - name: Build project
        run: yarn run build
        
      - name: Download project as artifact
        uses: actions/upload-artifact@main
        with:
          name: bundle
          path: ./WikiFine
